### PR TITLE
Updated project settings

### PR DESCRIPTION
**Pull request by amosavian**
This request creates separate frameworks for each target and added `libxml2.tbd` to `Linked frameworks` to resolve runtime linking issue, resolves issue #43

### CODE REVIEW

**Comment by cezheng** [comment]
I don't see why you roll back the project to the old 4-target way since having multiple targets with so many duplicated build settings is definitely not a good way to maintain the project.

For more information about having a single target for 4 platforms, you can refer to a blog post how PromiseKit does this.
http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

**Comment by amosavian** [comment]
because when I add it to iOS project and try to run, get this exception:

    dyld: Library not loaded: @rpath/Fuzi.framework/Fuzi
      Referenced from: (Project path)
     Reason: no suitable image found.  Did find: (macOS framework)

**Comment by cezheng** [comment]
@amosavian I would recommend you to use Carthage rather than adding the project directly to your, since Carthage builds a universal framework and you can choose to use Release or Debug configuration while dragging the project and the product framework in Xcode might end up using the one in the Debug build product folder.

Having one target definitely can definitely specify different configurations for different platforms if you had taken time to read that blog post I shared, it used this approach to configure the unit test framework.

The problem is not about maintaining 4 targets is difficult, it is about we don't know how many new platforms will be introduced by Apple in the future, and I definitely would prefer a more generic & sustainable way to maintain the project.

And I created a iOS project to try to reproduce your problem today, but it seems all went well so I don't really know what happened with your project.

**Comment by amosavian** [comment]
@cezheng I have problems with Submitting to Appstore
Check the answer on this question: http://stackoverflow.com/questions/26559948/found-an-unexpected-mach-o-header-code-1918975009-in-xcode-6

**Comment by cezheng** [comment]
don't know if you turned to Carthage or not, but since the framework should not contain iOS simulator binaries, you should add this step if you use Carthage: https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

**Pull request closed without merging**
